/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "royal-dark": "#050507",
        "royal-card": "#0d0e14",
        "gold-light": "#F5D77F",
        "gold-main": "#D4AF37",
        "gold-deep": "#AA771C",
        "gold-muted": "#9A8350",
        "surface-bright": "#f8f9ff",
        "secondary": "#0051d5",
        "tertiary-container": "#002109",
        "surface-container-high": "#dce9ff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "tertiary": "#000000",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#005320",
        "inverse-primary": "#bec6e0",
        "on-tertiary-container": "#009842",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "outline-variant": "#c6c6cd",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#002109",
        "tertiary-fixed-dim": "#62df7d",
        "primary": "#000000",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#00174b",
        "background": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#7ffc97",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#565e74",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#316bf3",
        "outline": "#76777d",
        "surface-container": "#e5eeff",
        "on-background": "#0b1c30",
        "on-secondary-fixed-variant": "#003ea8",
        "primary-fixed": "#dae2fd",
        "on-primary-container": "#7c839b",
        "on-secondary-container": "#fefcff",
        "surface-container-low": "#eff4ff",
        "secondary-fixed": "#dbe1ff"
      },
      spacing: {
        "spacing-lg": "1.25rem",
        "card-padding": "1rem",
        "spacing-xl": "1.5rem",
        "spacing-xs": "0.5rem",
        "spacing-2xs": "0.25rem",
        "spacing-2xl": "2rem",
        "spacing-3xl": "2.5rem",
        "spacing-sm": "0.75rem",
        "screen-margin": "1rem",
        "gutter-mobile": "1rem",
        "spacing-md": "1rem"
      },
      fontFamily: {
        "cinzel": ["Cinzel", "serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "amount-display": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "amount-row": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.3px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.4px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-md": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.2px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "amount-display": ["28px", { lineHeight: "34px", letterSpacing: "-0.5px", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "amount-row": ["16px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
